export type Achievement = {
  id: string;
  emoji: string;
  name: string;
  description: string;
  sarcasm: string;
};

export const ACHIEVEMENTS: Achievement[] = [
  // ── originais (baseados em dados reais) ──────────────────────────────
  {
    id: "sobrevivente",
    emoji: "🏆",
    name: "Sobrevivente",
    description: "7 dias usando o app",
    sarcasm: "Parabens, voce durou mais que seu plano de academia.",
  },
  {
    id: "maquina_humana",
    emoji: "🔥",
    name: "Maquina Humana",
    description: "5 dias verdes consecutivos",
    sarcasm: "Uau, voce e um ser humano funcional. Raridade.",
  },
  {
    id: "zumbi_funcional",
    emoji: "🧟",
    name: "Zumbi Funcional",
    description: "Recuperacao vermelha por 3+ dias e ainda acordou",
    sarcasm: "Seu corpo ta pedindo socorro mas voce ignorou. Respeito.",
  },
  {
    id: "rei_travesseiro",
    emoji: "😴",
    name: "Rei do Travesseiro",
    description: "Sono ruim por 5+ dias consecutivos",
    sarcasm: "Voce dorme mas nao descansa. Igual trabalhar de graca.",
  },
  {
    id: "campeao_sofa",
    emoji: "🛋️",
    name: "Campeao do Sofa",
    description: "Stress zero por 3+ dias seguidos",
    sarcasm: "Seu corpo nao fez nada. Literalmente nada. Orgulho.",
  },
  {
    id: "viciado_cafe",
    emoji: "☕",
    name: "Viciado em Cafe",
    description: "Stress alto por 3+ dias consecutivos",
    sarcasm: "Voce ta estressado ha dias. Tudo bem, o cafe tambem te ama.",
  },
  {
    id: "morto_vivo",
    emoji: "💀",
    name: "Morto-Vivo",
    description: "Vermelho por 3+ dias consecutivos",
    sarcasm: "Voce nao ta bem. Voce sabe disso. Todos sabem disso.",
  },
  {
    id: "atleta_mentira",
    emoji: "🥇",
    name: "Atleta de Mentira",
    description: "10+ dias de streak sem chegar a otimo",
    sarcasm: "10 dias monitorando sem melhorar. Comprometimento inutil.",
  },
  {
    id: "fantasma_academia",
    emoji: "👻",
    name: "Fantasma da Academia",
    description: "Primeira semana completa sem dia otimo",
    sarcasm: "Voce pagou a academia. So nao foi. Classico.",
  },
  {
    id: "ressaca_eterna",
    emoji: "🍺",
    name: "Ressaca Eterna",
    description: "HRV abaixo do normal por 7+ dias",
    sarcasm: "Seu coracao ta de ferias ha uma semana. Que sortudo.",
  },
  {
    id: "primeiro_verde",
    emoji: "⚡",
    name: "Flash Humano",
    description: "Primeiro dia verde",
    sarcasm: "Uau. Um dia bom. Anota ai, vai ser raro.",
  },
  {
    id: "ironman",
    emoji: "🦾",
    name: "Ironman",
    description: "30 dias de streak",
    sarcasm: "30 dias monitorando. Voce e louco ou disciplinado. Talvez os dois.",
  },

  // ── imagem 1 ─────────────────────────────────────────────────────────
  {
    id: "rei_depois_eu_faco",
    emoji: "🐌",
    name: "Rei do Depois Eu Faco",
    description: "Adiou o sync por 3+ dias seguidos",
    sarcasm: "Parabens! Voce adiou 12 coisas hoje.",
  },
  {
    id: "doutor_procrastinacao",
    emoji: "🦥",
    name: "Doutor em Procrastinacao",
    description: "Semana inteira sem um dia verde",
    sarcasm: "Voce levou jeito a outro nivel.",
  },
  {
    id: "cafe_nao_julga",
    emoji: "☕",
    name: "Cafe Nao Julga",
    description: "Stress alto por 7+ dias consecutivos",
    sarcasm: "Voce ja tomou 1000 cafes e continua cansado.",
  },
  {
    id: "especialista_desculpas",
    emoji: "🗑️",
    name: "Especialista em Desculpas",
    description: "Recuperacao laranja ou vermelha por 5+ dias",
    sarcasm: "Criatividade para nao fazer e o seu talento.",
  },
  {
    id: "bateria_social_esgotada",
    emoji: "🔋",
    name: "Bateria Social Esgotada",
    description: "Bateria critica (recuperacao < 30) por 2+ dias",
    sarcasm: "Interagiu com humanos. Precisa recarregar.",
  },
  {
    id: "derreteu_picole",
    emoji: "🍦",
    name: "Derreteu como Picole",
    description: "Recuperacao caiu 20+ pontos em 2 dias",
    sarcasm: "Tentou ser produtivo no calor. Deu ruim.",
  },
  {
    id: "modo_invisivel",
    emoji: "🕶️",
    name: "Modo Invisivel: Ativado",
    description: "Sem registrar dados por 5+ dias",
    sarcasm: "Voce some quando alguem pede um favor.",
  },
  {
    id: "nutricionista_caos",
    emoji: "🍕",
    name: "Nutricionista do Caos",
    description: "Stress > 30 min por 5 dias na semana",
    sarcasm: "Sua dieta hoje foi: o que tinha.",
  },
  {
    id: "atleta_sono",
    emoji: "🛏️",
    name: "Atleta do Sono",
    description: "Sono excelente mas recuperacao ruim",
    sarcasm: "Voce treina pesado... para dormir.",
  },
  {
    id: "maratonista_series",
    emoji: "🍿",
    name: "Maratonista de Series",
    description: "Sono acima de 85 por 10+ noites seguidas",
    sarcasm: "Voce assistiu mais de 10 episodios seguidos. Orgulho!",
  },
  {
    id: "artista_caos",
    emoji: "🗂️",
    name: "Artista do Caos",
    description: "Todos os 4 semaforos em uma semana",
    sarcasm: "Sua bagunca e inspiradora.",
  },
  {
    id: "ignorou_tudo",
    emoji: "🔔",
    name: "Ignorou Tudo",
    description: "Nenhum sync por 7+ dias",
    sarcasm: "999+ notificacoes e voce continua em paz.",
  },
  {
    id: "mestre_banho",
    emoji: "🛁",
    name: "Mestre do Banho",
    description: "Stress zero por 5+ dias seguidos",
    sarcasm: "Voce transformou banho em meditacao... de horas.",
  },
  {
    id: "genio_amanha",
    emoji: "🧠",
    name: "Genio do Ah, Amanha",
    description: "Nunca teve dia verde na primeira semana",
    sarcasm: "Solucoes brilhantes que sempre ficam para depois.",
  },
  {
    id: "sobrevivente_reunioes",
    emoji: "🌵",
    name: "Sobrevivente de Reunioes",
    description: "HRV acima de 70 por 5+ dias",
    sarcasm: "Voce poderia ter enviado um e-mail.",
  },
  {
    id: "viciado_tela",
    emoji: "📱",
    name: "Viciado em Tela",
    description: "Abre o app mais de 5x no mesmo dia",
    sarcasm: "Sua relacao com a tela e saudavel... sqn.",
  },
  {
    id: "ferias_mentais",
    emoji: "📋",
    name: "Ferias Mentais",
    description: "Sem dados por 4 dias no meio da semana",
    sarcasm: "Seu corpo esta aqui, mas sua mente nao.",
  },
  {
    id: "guerreiro_soneca",
    emoji: "⏰",
    name: "Guerreiro do Soneca",
    description: "Sono ruim por 3 dias seguidos",
    sarcasm: "Mais 5 minutinhos... que viraram horas.",
  },
  {
    id: "cabos_emocionais",
    emoji: "🧶",
    name: "Cabos Emocionais",
    description: "Stress e HRV ruins ao mesmo tempo por 3+ dias",
    sarcasm: "Sua vida e um emaranhado e voce abraca isso.",
  },
  {
    id: "rei_drama",
    emoji: "👑",
    name: "Rei do Drama",
    description: "Oscilou entre verde e vermelho na mesma semana",
    sarcasm: "Transforma qualquer coisa em novela.",
  },
  {
    id: "colecionador_roupa_suja",
    emoji: "🧺",
    name: "Colecionador de Roupa Suja",
    description: "15+ dias de dados acumulados",
    sarcasm: "Cheiro de sucesso.",
  },
  {
    id: "nao_perturbe_sempre",
    emoji: "🚫",
    name: "Nao Perturbe: Sempre",
    description: "Stress zero por 7+ dias seguidos",
    sarcasm: "Voce valoriza seu silencio (e seu isolamento).",
  },
  {
    id: "especialista_coracoes",
    emoji: "💔",
    name: "Especialista em Coracoes",
    description: "HRV abaixo de 40 por 5+ dias",
    sarcasm: "Deixou varios para depois. Inclusive o seu.",
  },
  {
    id: "campeao_desculpas",
    emoji: "🏅",
    name: "Campeao das Desculpas",
    description: "20 dias no app sem chegar a otimo",
    sarcasm: "Sempre tem uma, e bem ensaiada.",
  },
  {
    id: "fiesta_cancelamento",
    emoji: "🎉",
    name: "Fiesta do Cancelamento",
    description: "Cancelou o sync 3x na mesma semana",
    sarcasm: "Cancelou planos como ninguem. Voce e um icone.",
  },

  // ── imagem 2 ─────────────────────────────────────────────────────────
  {
    id: "nuvem_desculpas",
    emoji: "☁️",
    name: "Nuvem de Desculpas",
    description: "Recuperacao abaixo de 50 por 10+ dias",
    sarcasm: "Especialista em evitar responsabilidades.",
  },
  {
    id: "colecionador_talvezes",
    emoji: "🗑️",
    name: "Colecionador de Talvezes",
    description: "25+ dias acumulados com dados",
    sarcasm: "Voce guarda tudo que deveria ter feito.",
  },
  {
    id: "zero_novo_heroi",
    emoji: "💻",
    name: "Zero e o Novo Heroi",
    description: "Stress zero por todo um mes",
    sarcasm: "Voce fez absolutamente nada e esta orgulhoso.",
  },
  {
    id: "rolador_compulsivo",
    emoji: "📱",
    name: "Rolador Compulsivo",
    description: "Sono ruim + stress alto por 5+ dias",
    sarcasm: "Passou horas rolando e nao lembra de nada.",
  },
  {
    id: "decorador_cadeira",
    emoji: "🪑",
    name: "Decorador de Cadeira",
    description: "Stress > 60 min por 7 dias seguidos",
    sarcasm: "Deixou sua cadeira mais confortavel do que sua vida.",
  },
  {
    id: "sobrevivendo_1_porcento",
    emoji: "🔋",
    name: "Sobrevivendo no 1%",
    description: "Recuperacao entre 1 e 20 por 3+ dias",
    sarcasm: "Sua bateria e sua motivacao estao sempre no limite.",
  },
  {
    id: "gourmet_microondas",
    emoji: "🍕",
    name: "Gourmet de Micro-ondas",
    description: "Nunca teve sono excelente em 14 dias",
    sarcasm: "Sua culinaria se resume a esquentar.",
  },
  {
    id: "snooze_supremo",
    emoji: "⏰",
    name: "Snooze Supremo",
    description: "Sono ruim por 7+ dias consecutivos",
    sarcasm: "Campeao mundial de adiar a propria vida.",
  },
  {
    id: "estilista_preguica",
    emoji: "👕",
    name: "Estilista da Preguica",
    description: "Recuperacao amarela por 10+ dias seguidos",
    sarcasm: "Seu guarda-roupa tem uma peca oficial.",
  },
  {
    id: "planejador_nao_fazer",
    emoji: "📝",
    name: "Planejador de Nao Fazer Nada",
    description: "Todos os dias amarelos ou abaixo por 2 semanas",
    sarcasm: "Planejou tao bem que nao fez mesmo.",
  },
  {
    id: "inteligencia_sofa",
    emoji: "📺",
    name: "Inteligencia de Sofa",
    description: "HRV estavel mas recuperacao ruim por 5+ dias",
    sarcasm: "Assistiu, criticou e se sente especialista.",
  },
  {
    id: "vice_campeao_tudo",
    emoji: "🥈",
    name: "Vice-Campeao de Tudo",
    description: "Chegou a amarelo mas nunca a verde em 14 dias",
    sarcasm: "Chegou perto o suficiente pra receber o quase.",
  },
  {
    id: "arquiteto_sonhos",
    emoji: "📒",
    name: "Arquiteto de Sonhos",
    description: "Usou o app por 30 dias sem nunca ter 5 dias verdes seguidos",
    sarcasm: "Construiu grandes planos que nunca sairam do papel.",
  },
  {
    id: "night_owl",
    emoji: "🌙",
    name: "Night Owl (ou Coruja de Nada)",
    description: "HRV baixo mas stress zero por 5+ dias",
    sarcasm: "Fica acordado ate tarde sem motivo algum.",
  },
  {
    id: "pro_player_vida_real",
    emoji: "🎮",
    name: "Pro Player da Vida Real",
    description: "Recuperacao acima de 80 por 5+ dias",
    sarcasm: "Sua vida e um jogo no modo facil demais.",
  },
  {
    id: "empurrador_profissional",
    emoji: "📰",
    name: "Empurrador Profissional",
    description: "Streak de 14 dias sem nenhum verde",
    sarcasm: "Empurra tarefas como se fosse um esporte olimpico.",
  },
  {
    id: "terapeuta_sorvete",
    emoji: "🍨",
    name: "Terapeuta de Sorvete",
    description: "Stress alto por 3 dias mas sono bom",
    sarcasm: "Resolve 87% dos problemas com acucar.",
  },
  {
    id: "quebrador_metas",
    emoji: "🐷",
    name: "Quebrador de Metas",
    description: "Caiu de verde para vermelho em 2 dias",
    sarcasm: "Suas metas duram menos que sua dieta.",
  },
  {
    id: "rei_voltas",
    emoji: "🚫",
    name: "Rei das Voltas",
    description: "Oscilou entre verde e vermelho 3+ vezes",
    sarcasm: "Sempre volta pro mesmo ponto de partida.",
  },
  {
    id: "supervisor_caixas",
    emoji: "🐱",
    name: "Supervisor de Caixas",
    description: "Abriu o app todos os dias por 14 dias",
    sarcasm: "Se uma caixa existe, voce ja testou.",
  },
  {
    id: "monge_moderno",
    emoji: "🚫",
    name: "Monge Moderno",
    description: "Stress zero por 10+ dias seguidos",
    sarcasm: "Seu modo silencio e sagrado.",
  },
  {
    id: "alpinista_amanha",
    emoji: "🏔️",
    name: "Alpinista do Amanha",
    description: "Sempre no amarelo, nunca sobe para verde, por 3 semanas",
    sarcasm: "Sempre esta escalando pra ser feito depois.",
  },
  {
    id: "minimizador_tudo",
    emoji: "📋",
    name: "Minimizador de Tudo",
    description: "Recuperacao sempre abaixo de 65 por 21 dias",
    sarcasm: "Nada e importante o bastante para ser feito agora.",
  },
  {
    id: "lendario_desculpas",
    emoji: "⭐",
    name: "Lendario em Desculpas",
    description: "30 dias sem um dia verde sequer",
    sarcasm: "Voce nao falha... voce apenas explica muito bem.",
  },
];
